swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
schemes:
  - https
paths:
  /medications:
    get:
      summary: Returns a list of medications.
      description: Returns all medications.
      produces:
        - application/json
      responses:
        200:
          description: OK
